[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/en/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
